[build]
  publish = "public"
  command = "npm run build"

[[redirects]]
  from = "https://www.studio.wikiexplain.com"
  to = "https://es.estudio.wikiexplain.com"
  status = 301
  force = true
  conditions = {Language = ["es"]}

[[redirects]]
  from = "http://www.studio.wikiexplain.com"
  to = "https://es.estudio.wikiexplain.com"
  status = 301
  force = true
  conditions = {Language = ["es"]}

[[redirects]]
  from = "https://studio.wikiexplain.com/"
  to = "https://es.estudio.wikiexplain.com"
  status = 301
  force = true
  conditions = {Language = ["es"]}

[[redirects]]
  from = "http://studio.wikiexplain.com"
  to = "https://es.estudio.wikiexplain.com"
  status = 301
  force = true
  conditions = {Language = ["es"]}

[[redirects]]
  from = "studio.wikiexplain.com"
  to = "https://es.estudio.wikiexplain.com"
  status = 301
  force = true
  conditions = {Language = ["es"]}

[[redirects]]
  from = "www.studio.wikiexplain.com"
  to = "https://es.estudio.wikiexplain.com"
  status = 301
  force = true
  conditions = {Language = ["es
